### ISSUE TITLE
Example usage with Nuxt3

### ISSUE THREAD

**Issue by gregpalaci** [ferreira-tb/tauri-store#26]
Add this to `src/plugins` to make use in nuxt3

```
import type { PiniaPluginContext } from "pinia";
import { createPlugin } from "tauri-plugin-pinia";

export default defineNuxtPlugin(({ $pinia }) => {
	$pinia.use(createPlugin());
});
```

Thanks for the plugin, it's a dream and very powerful!

**Comment by ferreira-tb** [comment]
Hi, thank you for this. I'll make sure to update the docs with Nuxt examples.

**Comment by gregpalaci** [comment]
I explored nuxt modules too which might be better for a library but don't have enough expertise to write, the above plugin works well. Cheers
