### ISSUE TITLE
Question: would throttle vs/and or debounce be advantageous

### ISSUE THREAD

**Issue by gregpalaci** [ferreira-tb/tauri-store#27]
https://kettanaito.com/blog/debounce-vs-throttle

**Comment by ferreira-tb** [comment]
Good point. I think we can support both ways.

**Comment by ferreira-tb** [comment]
I just need to think about the API. I confess I didn't think about using throttle, so this might need to be a breaking change (so, 0.7).

**Comment by gregpalaci** [comment]
Yeah I think supporting both might be the best I'm not positive which would be better, but i think it might come down to the users use case, Can definitely steal the code to throttle / debounce from VueUse https://vueuse.org/shared/refDebounced/  or https://youmightnotneed.com/lodash#debounce / https://lodash.com/docs#throttle

In terms of performance I think it's more on the rust side of writing to file and making sure the operation is complete before allowing another write to file.

more reading https://css-tricks.com/debouncing-throttling-explained-examples/

I think throttle might be slightly better because it would only send a write operation once every x seconds which would be the latest resolved value

**Comment by gregpalaci** [comment]
Ah had a look at internals it's on the rust side  _interval_ would need to be reworked. Think probably not worth adding the throttle for now, the client side js can call "save" Vs autosave and wrap it themselves. Much less work for you and them.
