### ISSUE TITLE
Add Nuxt examples

### ISSUE THREAD

**Issue by ferreira-tb** [ferreira-tb/tauri-store#32]
See: https://github.com/ferreira-tb/tauri-store/issues/26

**Comment by jswhisperer** [comment]
If you need any contributors happy to help more :P

**Comment by ferreira-tb** [comment]
It would be really great, @jswhisperer, even if it's just some feedback on usage. I have some nice ideas for the plugin, but I'd also like to know how useful it's being to its users. There also might be features I haven’t considered yet that could be worth exploring.

**Comment by jswhisperer** [comment]
Happy to continue to help!
