### ISSUE TITLE
Save stores on change

### ISSUE THREAD

**Issue by ferreira-tb** [ferreira-tb/tauri-store#37]
Currently, stores can be saved manually, in a graceful exit, or periodically using `autosave`. We should also be able to save them whenever there is a state change.

**Comment by jswhisperer** [comment]
Should define state change maybe? is this on client side and any change to state? 
Does debounce or throttle settings effect this as set by user if so.

**Comment by ferreira-tb** [comment]
This would be an optional feature, available for both JavaScript and Rust.

```ts
import { useStore } from '@/stores';

const store = useStore();

// If the proposed feature is enabled, the store will automatically be saved to disk after this.
store.counter += 1;
```

Regarding debounce and throttle: yes, these options will be supported through the `save_strategy` option, which I’m currently working on and plan to include in version 0.9.

```rust
use tauri_plugin_pinia::SaveStrategy;

fn main() {
  // `Throttle` and `Immediate` are also available.
  let pinia = tauri_plugin_pinia::Builder::new()
    .save_strategy(SaveStrategy::debounce_secs(3))
    .build();

  tauri::Builder::default()
    .plugin(pinia)
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```

Just to clarify, the debounce and throttle options we have right now are for syncing the frontend with the backend, not for data persistence. Whenever the store state changes, it sends a notification to Rust to stay updated (or to JavaScript, if the change was made from Rust). Since data gets serialized every time this happens, these options are there to help prevent any performance slowdowns from too many updates.

On the other hand, the new `save_strategy` feature will focus on persistence and should work as expected when combined with the feature proposed in this issue.

**Comment by jswhisperer** [comment]
I'd imagine save_strategy to be <Bool> if possible then.
called as part of the init value and reading any debounce or throttle values.
Would be simpler to implement maybe and not a breaking change?

**Comment by ferreira-tb** [comment]
There are lot of changes coming in `v0.9`, but almost all of them are **not** breaking changes (including the `save_strategy`), just new nice things and performance improvements. 

Currently, the only breaking change will be [`Store::watch`](https://docs.rs/tauri-plugin-pinia/latest/tauri_plugin_pinia/struct.Store.html#method.watch) and [`Store::unwatch`](https://docs.rs/tauri-plugin-pinia/latest/tauri_plugin_pinia/struct.Store.html#method.unwatch), which will now require `&mut Self` instead of `&self`. However, this won’t affect anyone using only the JavaScript APIs.
