### ISSUE TITLE
Need to save twice to be effective

### ISSUE THREAD

**Issue by irongomme** [ferreira-tb/tauri-store#43]
I'm using the `saveAll` method manually, and here is what I have to do to make it work : 

```
export const saveSettings = async () => {
  ...
  await saveAll();
  await saveAll();
  ...
};
```

If i'm using only one, my stores are not saved into files.

**Comment by ferreira-tb** [comment]
Hi, thanks for reporting this.

I tried to reproduce the issue, but I wasn’t able to (using `saveAll` once worked as expected for me, as of `v0.8.2`). What are the exact versions of both the NPM package and the Rust crate that you're using? Are you using any specific Cargo features (e.g. `unstable-async`)?

If you could share a minimal reproducible example as well, it would really help.

**Comment by irongomme** [comment]
Of course, 

Here is `package.json` I'm using : 

```
"devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxt/eslint": "^0.7.2",
    "@nuxt/test-utils": "^3.15.1",
    "@nuxt/ui": "^2.19.2",
    "@pinia/nuxt": "^0.9.0",
    "@tauri-apps/cli": "^2.1.0",
    "@vitest/coverage-v8": "2.1.8",
    "@vue/test-utils": "^2.4.6",
    "eslint": "^9.16.0",
    "happy-dom": "^15.11.7",
    "husky": "^9.1.7",
    "nuxt": "^3.14.1592",
    "playwright-core": "^1.49.0",
    "prettier": "^3.4.2",
    "typescript": "^5.6.3",
    "vitest": "^2.1.8",
    "vue-tsc": "^2.1.10"
  },
  "dependencies": {
    "@faker-js/faker": "^9.3.0",
    "@iconify-json/icon-park-outline": "^1.2.1",
    "@iconify-json/icon-park-solid": "^1.2.1",
    "@tauri-apps/api": "^2.1.1",
    "@tauri-apps/plugin-process": "^2.0.0",
    "@tauri-apps/plugin-store": "^2.1.0",
    "@volar/language-server": "^2.4.10",
    "@vue/language-server": "^2.1.10",
    "fuse.js": "^7.0.0",
    "tauri-plugin-pinia": "^0.8.2",
    "uuid": "^11.0.3",
    "vue3-smooth-scroll": "^0.8.1",
    "zod": "^3.23.8"
  }
```

And part of my `Cargo.toml`

```
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.3", features = [] }

[dependencies]
log = "0.4"
tauri = { version = "2.1.1", features = [] }
tauri-plugin-log = "2.0.4"
tauri-plugin-store = "2.1.0"
tauri-plugin-pinia = "0.8.2"
tauri-plugin-process = "2.0.1"
```

And finally my `main.rs`

```
// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_pinia::init())
        .on_window_event(|_window, event| {
            if let tauri::WindowEvent::Destroyed = event {
                std::process::exit(0);
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");

    app_lib::run();
}
```

**Comment by irongomme** [comment]
After digging, I think this issue not directly linked to the plugin. 

In fact, I think this is related to store asynchronicity, because, if I replace the double saveAll with a setTimeout, I make it works as expected : 
```
myStore = useMyStore();
myStore.value = 'test';
setTimeout(saveAll, 50);
```

**Comment by ferreira-tb** [comment]
Oh, I see. That's probably the case. When a value in the store is updated, it triggers a synchronization process with the Rust backend. The `saveAll` command simply instructs the backend to save its current version to disk. However, if the synchronization hasn’t finished yet, Rust might still be working with outdated values. The `setTimeout` must have given it enough time to finish the synchronization.

I’m currently working on `v0.9`, which will introduce an option to save automatically whenever changes are made (without any synchronization issues like these) . I think this should be a great fit for your use case then.

**Comment by ferreira-tb** [comment]
Stores can now be saved automatically whenever their state is updated.

```ts
import { ref } from 'vue';
import { defineStore } from 'pinia';

function store() {
  const counter = ref(0);

  return {
    counter,
  };
}

export const useStore = defineStore('store', store, {
  tauri: {
    saveOnChange: true,
  },
});
```

For more details:
https://tb.dev.br/tauri-store/guide/persisting-state?plugin=tauri-plugin-pinia#save-on-change
